// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface CategoryPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  type?: string;
  description?: string;
  body_html?: string;
  comparison_html?: string;
  game_notes?: unknown;
  faqs?: unknown;
  related_categories?: unknown;
  source_taxonomy?: "genre" | "system" | "mechanic" | "theme" | "compatibility" | "decision_tag";
  source_term_slug?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Game {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  website_url?: string;
  image_url?: string;
  reviews_url?: string;
  review_summary?: string;
  blurb?: string;
  at_a_glance?: string;
  body_html?: string;
  notes?: string;
  rank?: number;
  is_free?: boolean;
  is_top_rated?: boolean;
  verified?: boolean;
  paid?: boolean;
  related?: unknown;
  publisher_or_creator?: string;
  submitted_by_visitor?: boolean;
  submitter_name?: string;
  submitter_email?: string;
  submission_notes?: string;
  min_players?: number;
  max_players?: number;
  gm_required?: boolean;
  gm_role_label?: string;
  session_length_minutes_min?: number;
  session_length_minutes_max?: number;
  prep_level?: "none" | "low" | "medium" | "high";
  one_shot_friendly?: boolean;
  campaign_friendly?: boolean;
  solo_friendly?: boolean;
  beginner_friendly?: boolean;
  complexity_score?: number;
  setup_minutes?: number;
  character_creation_minutes?: number;
  new_gm_friendly?: number;
  improv_burden?: "none" | "low" | "medium" | "high";
  structure_level?: "guided" | "balanced" | "open";
  combat_focus?: number;
  roleplay_focus?: number;
  tactical_depth?: number;
  campaign_depth?: number;
  price_model?: "free" | "paid" | "pwyw";
  quickstart_available?: boolean;
  pdf_available?: boolean;
  physical_book_available?: boolean;
  vtt_ready?: boolean;
  content_intensity?: "low" | "medium" | "high";
  best_for?: unknown;
  avoid_if?: unknown;
  why_it_fits?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    category_pages: CategoryPage;
    games: Game;
    pages: Page;
    posts: Post;
  }
}