// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface CategoryPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  type?: string;
  description?: string;
  body_html?: string;
  comparison_html?: string;
  game_notes?: unknown;
  faqs?: unknown;
  related_categories?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Game {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  website_url?: string;
  image_url?: string;
  reviews_url?: string;
  review_summary?: string;
  blurb?: string;
  at_a_glance?: string;
  body_html?: string;
  notes?: string;
  rank?: number;
  is_free?: boolean;
  is_top_rated?: boolean;
  verified?: boolean;
  paid?: boolean;
  related?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    category_pages: CategoryPage;
    games: Game;
    pages: Page;
    posts: Post;
  }
}